"""
format_writers.py - Additional output format writers.

Provides CSV, Kingdom SMT, and SonarWiz tide file outputs
alongside the default .tid format.
"""

import logging
from typing import List

from data_io.navigation import NavPoint

logger = logging.getLogger(__name__)


def write_csv(output_path: str, nav_points: List[NavPoint], config) -> None:
    """
    CSV output: Time, Lat, Lon, Tc_m, Tc_cm

    Args:
        output_path: Output file path (.csv).
        nav_points: Processed NavPoint list.
        config: TideBedConfig.
    """
    if not nav_points:
        logger.warning("CSV 출력: Nav 포인트가 없습니다")
        return

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("Time,Latitude,Longitude,Tc_m,Tc_cm\n")
        for nav in nav_points:
            tc_cm = nav.tc if nav.tc > -999.0 else -999.0
            tc_m = tc_cm / 100.0 if tc_cm > -999.0 else -9.99
            time_str = nav.t.strftime("%Y/%m/%d %H:%M:%S")
            f.write(f"{time_str},{nav.y:.7f},{nav.x:.7f},{tc_m:.4f},{tc_cm:.2f}\n")

    logger.info(f"CSV 출력 완료: {len(nav_points)}개 레코드 -> {output_path}")


def write_kingdom_tide(output_path: str, nav_points: List[NavPoint], config) -> None:
    """
    Kingdom SMT tide gate format.

    Header: // Kingdom tide correction
    Data:   YYYY/MM/DD HH:MM:SS  Tc_m

    Args:
        output_path: Output file path (.kingdom.txt).
        nav_points: Processed NavPoint list.
        config: TideBedConfig.
    """
    if not nav_points:
        logger.warning("Kingdom 출력: Nav 포인트가 없습니다")
        return

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("// Kingdom tide correction\n")
        f.write(f"// Generated by TideBedPy\n")
        f.write(f"// Points: {len(nav_points)}\n")
        for nav in nav_points:
            tc_m = nav.tc / 100.0 if nav.tc > -999.0 else -9.99
            time_str = nav.t.strftime("%Y/%m/%d %H:%M:%S")
            f.write(f"{time_str}  {tc_m:.3f}\n")

    logger.info(f"Kingdom 출력 완료: {len(nav_points)}개 레코드 -> {output_path}")


def write_sonarwiz_tide(output_path: str, nav_points: List[NavPoint], config) -> None:
    """
    SonarWiz tide format.

    Header: #SonarWiz Tide File
    Data:   YYYY-MM-DDTHH:MM:SS  Tc_m

    Args:
        output_path: Output file path (.sonarwiz.txt).
        nav_points: Processed NavPoint list.
        config: TideBedConfig.
    """
    if not nav_points:
        logger.warning("SonarWiz 출력: Nav 포인트가 없습니다")
        return

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("#SonarWiz Tide File\n")
        f.write(f"#Generated by TideBedPy\n")
        f.write(f"#Points: {len(nav_points)}\n")
        for nav in nav_points:
            tc_m = nav.tc / 100.0 if nav.tc > -999.0 else -9.99
            time_str = nav.t.strftime("%Y-%m-%dT%H:%M:%S")
            f.write(f"{time_str}  {tc_m:.3f}\n")

    logger.info(f"SonarWiz 출력 완료: {len(nav_points)}개 레코드 -> {output_path}")
